# Generated by Django 2.2.13 on 2021-03-08 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Imagen de Perfil'),
        ),
    ]
