# Generated by Django 2.2.13 on 2021-08-25 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre Hotel')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('pais', models.CharField(max_length=100, verbose_name='Pais')),
                ('comunidad', models.CharField(blank=True, default='', max_length=200, verbose_name='Comunidad')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, verbose_name='Direccion')),
                ('correo', models.EmailField(max_length=254, verbose_name='correo')),
                ('descripcionRapida', models.TextField(default='', verbose_name='Descripcion rapida')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hoteles',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Comentario', models.TextField(max_length=500, verbose_name='comentario')),
                ('sentiment', models.BooleanField(verbose_name='sentiment')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Hotel')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
