# Generated by Django 2.2.13 on 2021-08-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre'),
        ),
    ]
