# Generated by Django 2.2.13 on 2021-08-25 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_comentario_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='Comentario',
            new_name='comentario',
        ),
    ]
